### ISSUE TITLE
When Scrobbled using filename, get data from Simkl.

### ISSUE THREAD

**Issue by kat953162** [SIMKL/script.simkl#11]
Discussion of this issue in #4

Essentially, if there is no IMDb/tvdb data, it shows the filename in the bubble instead of having the data from Simkl response.

**Comment by daviddavo** [comment]
I think it is fixed. But let's try it first.

[script.simkl.zip](https://github.com/SIMKL/script.simkl/files/721121/script.simkl.zip)

**Comment by daviddavo** [comment]
By the way, I did not test it with movies. I do not have any movies that are not recognised by Kodi

**Comment by kat953162** [comment]
To get videos to not be recognized by Kodi, they need to not be a part of your library, and you have to open them through Videos/Files/

**Comment by daviddavo** [comment]
Working both with movies and series. I think it's ready to commit, but let's try it first

[script.simkl.zip](https://github.com/SIMKL/script.simkl/files/721775/script.simkl.zip)

**Comment by ekleop** [comment]
Thank you, now it works like a charm
