### ISSUE TITLE
compdate.txt file error

### ISSUE THREAD

**Issue by ekleop** [SIMKL/script.simkl#12]
On windows I have this error because I cannot execute tozip.sh and create the file

`15:08:09 T:9872   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', 'C:\\Users\\Eugene\\AppData\\Roaming\\Kodi\\addons\\simkl-master/resources/data/compdate.txt')
                                            Traceback (most recent call last):
                                              File "C:\Users\Eugene\AppData\Roaming\Kodi\addons\simkl-master\service.py", line 19, in <module>
                                                with open(os.path.dirname(os.path.realpath(__file__)) + "/resources/data/compdate.txt", "r") as f:
                                            IOError: (2, 'No such file or directory', 'C:\\Users\\Eugene\\AppData\\Roaming\\Kodi\\addons\\simkl-master/resources/data/compdate.txt')
                                            -->End of Python script error report<--
15:08:09 T:9872    INFO: Python script stopped`

**Comment by ekleop** [comment]
If not use http://take.ms/6KJm1 and just download zip file it works

**Comment by daviddavo** [comment]
It works, but there are some functions that don't work. Like logging in, for example.

You should download it from here https://github.com/SIMKL/script.simkl/releases/latest

[script.simkl.zip](https://github.com/SIMKL/script.simkl/files/718533/script.simkl.zip)
