### ISSUE TITLE
Doesn't work on Android Kodi versions

### ISSUE THREAD

**Issue by kat953162** [SIMKL/script.simkl#14]
Will try to get logs to you, but basically it says it scrobbles but it doesn't. This narrows out phones and TV boxes, sticks, etc.

Probably should fix this before getting Kodi repo

**Comment by kat953162** [comment]
Correction, with v1 update. Doesn't even log in anymore, says check log. Please try to fix it if possible. I can get the log soon

**Comment by daviddavo** [comment]
I installed an Android Virtual Box. Is this in your log?

`albumview.idAlbum = albumartistview.idAlbum ORDER BY albumview.idAlbum desc, albumartistview.iOrder
10:24:37 T:18446744072761641248   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', u'/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/script.simkl/simkl_key')
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.simkl/service.py", line 11, in <module>
                                                from resources.lib import interface, engine
                                              File "/storage/emulated/`

**Comment by daviddavo** [comment]
Last error fixed: Test version:
[script.simkl.zip](https://github.com/SIMKL/script.simkl/files/737010/script.simkl.zip)

**Comment by daviddavo** [comment]
Good news everyone! I tested it with virtual box, with that zip, and It's scrobbling

**Comment by kat953162** [comment]
That test zip didn't work for me, unfortunately.
 
It says check the log, after installing and when pressing login.

**Comment by kat953162** [comment]
I will see if I get the same error in Remix OS (a version of Android on my PC) and if that acts differently from Android X86 in virtualbox

**Comment by kat953162** [comment]
If possible, make make this issue a low priority because I stopped primarily using Kodi on Android. It works great on Linux and Windows. 

I will gladly test on Android, as I have Remix OS as well as my OnePlus 3 smartphone (running current versions of Android)

**Comment by kat953162** [comment]
Testing on Android...

1. Install went fine.
2. There were duplicate PIN screens, but unlike on Windows, the first PIN actually works (clicked cancel for second PIN screen).

Will make another comment after testing a file in and out of the Kodi library.

**Comment by daviddavo** [comment]
Now I have an android tablet, and it worked perfectly. Closing this issue
