### ISSUE TITLE
Kodi 17, installation broken

### ISSUE THREAD

**Issue by ekleop** [SIMKL/script.simkl#16]
After the add-on was downloaded it threw an error
`16:43:12.170 T:12816   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', u'C:\\Users\\Eugene\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            Traceback (most recent call last):
                                              File "C:\Users\Eugene\AppData\Roaming\Kodi\addons\script.simkl\service.py", line 11, in <module>
                                                from resources.lib import interface, engine
                                              File "C:\Users\Eugene\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\interface.py", line 7, in <module>
                                                from simklapi import api as API
                                              File "C:\Users\Eugene\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\simklapi.py", line 21, in <module>
                                                with open(USERFILE, "w+") as f:
                                            IOError: (2, 'No such file or directory', u'C:\\Users\\Eugene\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.simkl\\simkl_key')
                                            -->End of Python script error report<--`

There is no "script.simkl" directory, for some reason it wasn't created

**Comment by kat953162** [comment]
I get this type of error on Android, but I run Kodi 17 on Android and 16 on
my computers

**Comment by ekleop** [comment]
So now we know it's on windows too, I think it is common problem for Kodi 17

**Comment by kat953162** [comment]
I have a copy of Kodi 17 on Windows (its under the Windows Store). I will
try it out there too
