### ISSUE TITLE
Simkl account authorization raspberry pi bug

### ISSUE THREAD

**Issue by joggs** [SIMKL/script.simkl#17]
Hi,
I'm running kodi on raspberry pi 3 and when i try to authorize the pi for using simkl, eg when the "please visit simkl.com/pin prompt pops up in kodi, I go to that url in a web browser, but i never get the chance to enter a code as i am directly redirected to the simkl first page. The prompt still remains on the rpi and i have to cancel...the plugin never gets authorized.

The same use case on android was almost the same, the prompt in kodi in android, BUT, when i enter the simkl.com/pin, i get redirected without entering a code, BUT android seems to recognize this, and the app in kodi is authorized (even though i don't enter the code).

So the most logical would be that you always have to enter the code on simkl.com/pin, and not get redirected befor entering a code, as this would give the plugin a chance to poll for the auth.response no matter the OS.

UPDATE: It works when I am using safari browser, but not with chrome. Maybe you want to close this issue. weird.

**Comment by daviddavo** [comment]
It's an API issue, btw. I think it has something to do with connecting from the same network or something like this.

**Comment by ekleop** [comment]
You can test it now, it should work.
