### ISSUE TITLE
Not scrobbling files that aren't in library on some devices

### ISSUE THREAD

**Issue by kat953162** [SIMKL/script.simkl#24]
Currently, all of my devices have the latest version (at least according to the version number).

On my Linux device, if I have a file not in my library, it scrobbles fine.

On my Windows device, if I have a file not in my library, it fails to scrobble.

I primarily use Windows for video watching, with some exceptions.

**Comment by kat953162** [comment]
Update: On my Linux device, if I watch a file IN my library, it fails to scrobble. If it's not in my library, it scrobbles fine.

**Comment by kat953162** [comment]
Update 2:
on Windows it scrobbles for everything.
on Linux, it appears to fail to scrobble for everything but I will do more testing to confirm.

**Comment by kat953162** [comment]
Update 3: definitely not scrobbling often. Is there an ETA on library sync?

**Comment by kat953162** [comment]
Update 4:
NOT scrobbling on Windows for files in library. Scrobbling for non-library files occurs.
On Linux, I need to test further.

**Comment by kat953162** [comment]
Update 5:
Linux and Windows: Scorbbles random files not in library
Linux and Windows: **Doesn't scrobble** Library items

**Comment by kat953162** [comment]
Update 6:
Fresh Kodi install. Here are logs of 2 files, one that is in the library (doesn't scrobble) and one that is not in the library (scrobbles). This is on Windows 10.

File in Kodi Library: https://gist.github.com/kat953162/d835e79fc2f919042b018038bcea62a9
File *not* in Kodi Library https://gist.github.com/kat953162/e0f488be89a8ce52d0a013653a150d6d

**Comment by kat953162** [comment]
UPDATE 7: A show in my library just scrobbled, Kodi 18 on Windows. Will test a show that isn't in the library soon.

**Comment by ekleop** [comment]
check it now, should be fixed
