### ISSUE TITLE
Kodi 17, login window pops up twice

### ISSUE THREAD

**Issue by ekleop** [SIMKL/script.simkl#25]
According to logs, login dialog popped up twice, so the window showed me the code '112233' but it's waiting for code '444444' because it got it when the window was displayed the second time. So I can't to log in

`11:20:43.840 T:12260   DEBUG: Thread BackgroundLoader 12260 terminating
11:20:43.861 T:5024   DEBUG: Simkl: APIFILE: C:\Users\Eugene\AppData\Roaming\Kodi\addons\script.simkl\resources\data\apikey
11:20:43.861 T:5024   DEBUG: Simkl: {
                                              "apikey":"........",
                                              "secret":"......."
                                            }
11:20:43.861 T:5024   DEBUG: Simkl: APIKEY: .............
11:20:44.047 T:5024   DEBUG: Simkl: Usersettings: {u'error': u'user_token_failed'}
11:20:44.047 T:5024   DEBUG: Simkl: Icon: C:\Users\Eugene\AppData\Roaming\Kodi\addons\script.simkl\resources\icon.png
11:20:44.054 T:5024   DEBUG: Simkl dir: C:\Users\Eugene\AppData\Roaming\Kodi\
11:20:44.054 T:5024   DEBUG: Simkl | Python Version: 2.7.11 (default, Jan 16 2016, 16:21:17) [MSC v.1900 32 bit (Intel)]
11:20:44.054 T:5024   DEBUG: Simkl | ['']
11:20:44.054 T:5024   DEBUG: Simkl | compdate: 2017-05-13 21:36:45+02:00
11:20:44.054 T:5024   DEBUG: Simkl: User not logged in
11:20:44.082 T:9992   DEBUG: Simkl: Userfile
11:20:44.083 T:9992   DEBUG: Simkl: APIFILE: C:\Users\Eugene\AppData\Roaming\Kodi\addons\script.simkl\resources\data\apikey
11:20:44.083 T:9992   DEBUG: Simkl: {
                                              "apikey":".......",
                                              "secret":".........."
                                            }
11:20:44.083 T:9992   DEBUG: Simkl: APIKEY: ...........
11:20:44.349 T:9992   DEBUG: Simkl: Usersettings: {u'error': u'user_token_failed'}
11:20:44.349 T:9992   DEBUG: Simkl: Icon: C:\Users\Eugene\AppData\Roaming\Kodi\addons\script.simkl\resources\icon.png
11:20:44.351 T:9992   DEBUG: Simkl dir: C:\Users\Eugene\AppData\Roaming\Kodi\`

and 1 minute later some error was thrown
`11:21:01.832 T:1592   ERROR: Exception in thread Thread-1:
                                            Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi17\system\python\Lib\threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "C:\Program Files (x86)\Kodi17\system\python\Lib\threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "C:\Users\Eugene\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\interface.py", line 52, in threaded
                                                if self.check_login(self.pin, self.log):
                                              File "C:\Users\Eugene\AppData\Roaming\Kodi\addons\script.simkl\resources\lib\simklapi.py", line 110, in check_login
                                                if r["result"] == "OK":
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
11:21:07.834 T:4860   DEBUG: Simkl: Still waiting... 24`

**Comment by kat953162** [comment]
I got this too.

Fresh install of Kodi, installed Simkl service.

Pops up... I enter the PIN online. Popup doesn't disappear.
I press "back" button to escape it, and I see another window with another PIN.
Enter that PIN online, and the popup closes itself.

**Comment by daviddavo** [comment]
For the logs it seems that kodi runs the main script twice...

**Comment by daviddavo** [comment]
I can't reproduce the problem with latest kodi build

**Comment by kat953162** [comment]
You need to wipe the Kodi data too, since uninstalling the addon or Kodi doesn't remove the data.

**Comment by kat953162** [comment]
This isn't the biggest priority, its just really annoying to deal with.

**Comment by ekleop** [comment]
It should be fixed right now
