### ISSUE TITLE
Login is complicated

### ISSUE THREAD

**Issue by kat953162** [SIMKL/script.simkl#27]
Many problems with the PIN. Its hit-and-miss.

1. There are often double screens, and the first one doesn't work
2. It is difficult to trigger the PIN screen
3. The login link rarely works, usually you need to uninstall/reinstall the addon to get the PIN screen(s).

**Comment by ekleop** [comment]
Please test it now. Everything should be ok

**Comment by daviddavo** [comment]
Yeah, It seems to work, I'll push it into Kodi repositories ASAP

**Comment by ekleop** [comment]
Maybe we should fix #24 first and then push it

**Comment by daviddavo** [comment]
I don't know when I'll fix it, so I'll push it now

**Comment by ekleop** [comment]
ok, let's us check it first, i think we can fix it. Then you can push
