### ISSUE TITLE
Intervals for Failed attempts to Scrobble

### ISSUE THREAD

**Issue by kat953162** [SIMKL/script.simkl#29]
Currently, it appears that when the internet is disconnected or unstable and the plugin fails to scrobble, it retries every 5 seconds or so. This is disruptive to the viewer.

A user-friendly solution would be to do this:

Section A:
**Attempt to scrobble**
Does it succeed?
Yes - notify the user and end.
No - notify the user and **start Section B**.

Section B:
30 second interval
**Attempt to scrobble**
Does it succeed?
Yes - Notify the user and end.
No - Don't notify the user and **restart section B**.
**If at 95% of video, start Section C.**

Section C:
At 95% of the video, has it scrobbled yet?
Yes - Do nothing
No - Notify the user

_Using this logic, the user will not be pestered with repetitive messages but will instead receive no more than 2 total notifications during the video._

**Comment by ekleop** [comment]
If we do not show the notification to the user, then he will think that this is a bug because his tv show wasn't marked.  So I think we have to display it at least once.

**Comment by daviddavo** [comment]
It seems easy, I'll try to do is between today and tomorrow

**Comment by kat953162** [comment]
@ekleop See section A. It does notify the user the first time. But only the first time and at 95%.

**Comment by kat953162** [comment]
@daviddavo Awesome!

**Comment by ekleop** [comment]
@kat953162 yeap, you're right.

**Comment by kat953162** [comment]
I only noticed the "retry" thing today because my WiFi router keeps disconnecting randomly. Not sure when the feature was added.

**Comment by ekleop** [comment]
It was added a week ago or more precisely, it was added a long time ago but didn't work correctly

**Comment by daviddavo** [comment]
Please test it before serializing the strings

**Comment by ekleop** [comment]
Cool, will test it tomorrow

**Comment by ekleop** [comment]
Have tested, everything works fine, but have few suggestions

1. ` while not success:
                        log("Retrying")`
This code breaks main loop. If scrobble failed and then user stops the movie, thread won't stop. We cannot stop the `_thread_tracker` from outside because **"retry while"** blocks the thread. `self._playback_lock.isSet()` check never happens until we scrobble

2. `except:
                self._playback_lock.clear()` if you modify the case above, then this is not needed anymore, because if we exited from the loop then we have already cleared it or kodi died
