### ISSUE TITLE
Rescrobbling

### ISSUE THREAD

**Issue by kat953162** [SIMKL/script.simkl#3]
It scrobbles every few minutes after a certain point. It should only scrobble once.

**Comment by kat953162** [comment]
My logfile (only the relevant part at the end): http://paste.ubuntu.com/23731882/

It even scrobbles when the video is paused (timer of some sort).

**Comment by daviddavo** [comment]
Btw, yes, it has a timer. Every 120 seconds or so it checks how the scrobble is going

**Comment by kat953162** [comment]
It still shows the bubble.
