### ISSUE TITLE
Trailers are marked as watched too

### ISSUE THREAD

**Issue by ekleop** [SIMKL/script.simkl#30]
According to this https://forum.kodi.tv/showthread.php?tid=305324&pid=2619458#pid2619458
I think it should check also total time of the file(before the tracker_thread started). if it's less than 10 minutes skip the file and do not start tracker_thread.

**Comment by daviddavo** [comment]
One of the problem is that there are TV Shows that have chapters of 4-5 minutes...

**Comment by ekleop** [comment]
so.. then we can take 4 minutes, I think it's pretty rare for trailers to be longer

**Comment by ekleop** [comment]
The problem still exists. Almost all trailers are longer than 3-4minutes(apr 5-7). So we should make at least 8 minutes for scrobble or even add an option to the settings menu for users who watch short TV Show.

**Comment by daviddavo** [comment]
Added an option on settings which lets the user decide the minimum length of the file to scrobble (default to 5 minutes). Useful meanwhile we discover how to detect if it is a trailer by other methods.
