### ISSUE TITLE
Scrobbles on Start when video hasn't loaded

### ISSUE THREAD

**Issue by kat953162** [SIMKL/script.simkl#31]
This issue isn't easy to reproduce so I will just explain the problem and what can possibly be done to fix it:

Problem: Occasionally, if a video is opened, it might scrobble instantly when it starts playing. This is because the video hasn't "loaded" yet. it scrobbles at 70 percent... so if the whole video hasn't loaded yet (doesn't even have a length of video file), it will scrobble instantly because it thinks 100 percent has played.

Possible Solution: Ensure that the Addon doesn't scrobble unless at *least* one minute has played or that its 70 (or whatever is designated) percent of the usual episode length.

**Comment by ekleop** [comment]
yes, there is such problem. Will be fixed in the next release

**Comment by daviddavo** [comment]
Done, I'll upload it on the next commit

**Comment by ekleop** [comment]
Nice, I think after #30  we can make a push to the kodi's repo. After global testing of course

**Comment by kat953162** [comment]
Just wanted to say this issue is still persistent on occasion. Sometimes it might scrobble at the beginning or at 15 percent in, as the addon can't seem to get the episode length.

Perhaps if the addon pinged Simkl to determine the supposed episode length, it can avoid the issue of early false scrobbles. Can try to log this some time.
