### ISSUE TITLE
Notifications make the video freeze for a bit on some devices.

### ISSUE THREAD

**Issue by kat953162** [SIMKL/script.simkl#32]
The description is in the title. Not all devices have this problem. It has been existent for a while now but I never bothered to report the issue. 

If some sort of animation could be removed from the notification bubble, that might fix the problem. 

Currently on Estuary but other themes do it as well.

**Comment by daviddavo** [comment]
There is no "animation", the only thing you can do is deactivating the bubble in the options.
Maybe what causes the "freezing" is not the notification but the plugin itself (trying to sending it to kodi)
