### ISSUE TITLE
Bubbles

### ISSUE THREAD

**Issue by kat953162** [SIMKL/script.simkl#4]
Good: Bubbles contain episode title. 
Bad: Bubbles don't contain TV show name or episode number.

**Comment by daviddavo** [comment]
Now the format is: "Example Series S42E37"

**Comment by ekleop** [comment]
https://monosnap.com/file/t7igl2WmBRPU9V1g5fJa1LUg9pGRaz
http://take.ms/nlPG8
unfortunately it still shows filename for me.
windows, latest version

**Comment by kat953162** [comment]
I don't believe it ever showed filenames for me. That is because my Kodi
library is organized for my TV shows. It appears that you are going to
Videos/Files to open your shows. (uses TheTVDB)

**Comment by kat953162** [comment]
ekleop: Your Kodi library isn't organized to sort TV shows. It appears that you are opening them by Videos/Files. When adding a directory to Kodi, make sure to "set content" to TV shows.

**Comment by ekleop** [comment]
Yeap you're right, but Simkl returns TV Show name and episode(as you can see on screen), why we cannot take them if we haven't info from kodi?

**Comment by kat953162** [comment]
ekleop: Not really sure how Kodi processes movie files since I don't watch movies (only TV) but a quick look at the set content setting to add movies seems like your method would work if your movies were together. [screenshot](https://puu.sh/tkZu8/399332b114.png)

For tv shows, I have every show in its own directory, often in multiple locations. Kodi reads them all and grabs them into a TV section of the Kodi library. [screenshot](https://puu.sh/tkZxx/346fd99421.png)

Possibly Simkl can detect it (I believe the Windows tracker does) but for now, I recommend you organize your Kodi library. I can help you do so if necessary (TeamViewer or hangouts/whatsapp/facebook). 

Ever since I started using Kodi, I never need to see a filename of a TV show to ruin the experience.

Current setup (with library, no filenames): https://puu.sh/tl00u/1781c91a7a.png
Former setup (no library, ugly filenames): https://puu.sh/tl09Y/1f69c32952.png

**Comment by ekleop** [comment]
Yes I agreed that organized library looks better but I have 5-10 files only and I always delete old or watched files. So organizing for me is just time wasting.  Every user has their preference and I think it's not too hard  put an info from Simkl to the bubble for users like me ;)

**Comment by ekleop** [comment]
i'm totally agree with you, but still it doesn't mean that the addon shouldn't display TV Show title for that files when this is possible.

**Comment by kat953162** [comment]
Ekleop: I am thinking this feature should have its own issue. #11

**Comment by kat953162** [comment]
It is possible because the Windows tracker could do it.
