### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by kat953162** [SIMKL/script.simkl#5]
Even after you are logged in, it shows the login button.

It should instead say who is logged in, and provide a way to disconnect or change the login.

**Comment by daviddavo** [comment]
Now it shows a label after clicking in the Login button, and a Warning with your username if you click on it.
I don't know if I can change labels from the setting menu without having to restart Kodi.

[script.simkl.zip](https://github.com/SIMKL/script.simkl/files/706483/script.simkl.zip)

**Comment by kat953162** [comment]
I haven't tried the zip yet, but make it something generic like add/change user,

**Comment by daviddavo** [comment]
I can do that. With Kodi, you can change between labels, but not setting a current label. So we could have a "login" label and a "change user" label.

**Comment by kat953162** [comment]
Can you make sure to add the "latest" version to the main page? For the past week, it didn't have the correct latest copy (it had the one with the rescrobbling issue)

Thanks

**Comment by daviddavo** [comment]
I published it this morning in

https://github.com/SIMKL/script.simkl/releases
