### ISSUE TITLE
Movies in Recently Watched	

### ISSUE THREAD

**Issue by TasTraceur** [SIMKL/script.simkl#56]
I think there is a problem with the movies. It marks them as views, yes, but it should not set the date or something, because the movies do not appear as recently watched. With the series it works well.

**Comment by TasTraceur** [comment]
Checking the Simkl export csv, I think the problem is that if the movie was pending to see (plan to watch), when marking it as complete, the simkl add-on for kodi does not update the date, it keeps the date of when it was marked as pending. I think that updating the date (even if it exists) in the add-on would be solved and I think it would be correct (as long as Simkl allows update the "WatchedDate").

**Comment by ekleop** [comment]
Thank you for detailed info, fixed. Could you confirm?

**Comment by TasTraceur** [comment]
Yes, I saw a movie marked as "Plan to Watch" and when the add-on marked it as Watched, it appear in my recently watched. Thanks, good job ;)
