### ISSUE TITLE
Doesn't work with Kodi 19

### ISSUE THREAD

**Issue by ekleop** [SIMKL/script.simkl#59]
Perhaps, because of python 3

**Comment by marvin8** [comment]
Can confirm... the Simkl Kodi addon has stopped working since I've upgraded to Kodi 19.

For what it's worth, I am using an Android Based "set-top box"

**Comment by mrgreaper** [comment]
been redirected to this issue, but not sure what the solution is?

**Comment by masyk** [comment]
We haven't had time to look closely on the issue yet, there is currently no solution until we rework it to support python 3. Please use Kodi 18 for now.

**Comment by mrgreaper** [comment]
Ah, no solution explains why I couldnt find it lol. 
Will go simkl-less until its fixed (never keen on dropping down a version on software and getting kodi to play ball with my home media was a pain).

**Comment by kat953162** [comment]
Using PlexKodiConnect is a temporary failsafe that scrobbles most of my content through webhooks with Plex Pass, and can also use Tautulli method if needed.

**Comment by marvin8** [comment]
I've just created a PR with what I think are minimal changes to make this addon work with Kodi 19.

I have tested this with Kodi 19 on my Manjaro install and on my Android set-top box.

**Comment by ekleop** [comment]
> I've just created a PR with what I think are minimal changes to make this addon work with Kodi 19.
> 
> I have tested this with Kodi 19 on my Manjaro install and on my Android set-top box.

Hi, I'll check it in a few days, mb friday
