### ISSUE TITLE
Data to mark

### ISSUE THREAD

**Issue by kat953162** [SIMKL/script.simkl#6]
Even though some most shows get marked, there are some that don't.

It appears as if it marks the title of the show/movie to Simkl.

If instead, it scrobbled to Simkl using information from TheTVDB and IMDB, (and if that information wasn't available, try filename), then there is a higher chance that the scrobbling would work more successfully.

Keep up the excellent work!

**Comment by daviddavo** [comment]
It uses IMdb, and if this isn't available, filename, but I was going to include tvdb as well

**Comment by kat953162** [comment]
Have you added thetvdb yet?

**Comment by daviddavo** [comment]
@kat953162 No, I can't find a method either with the Python or libraries.

**Comment by kat953162** [comment]
This is a lower priority because it works at the moment :)

It can be resolved after Kodi Repo accepts the app

**Comment by daviddavo** [comment]
tvdbid added on https://github.com/SIMKL/script.simkl/commit/78d23b3867e8ebaf0f4a11facd51bcdd6180f9cd
