### ISSUE TITLE
Installation instructions do not work (not appearing in the list)

### ISSUE THREAD

**Issue by mrgreaper** [SIMKL/script.simkl#62]
Fresh install of windows and a fresh install of kodi and Simkl is not in Services. 
![image](https://user-images.githubusercontent.com/2314200/110252222-3feb7580-7f7c-11eb-8747-d45cba7788a0.png)

**Comment by masyk** [comment]
Does not currently work in new Kodi 19. See issue https://github.com/SIMKL/script.simkl/issues/59
