### ISSUE TITLE
Not possible to re-login

### ISSUE THREAD

**Issue by SntNick** [SIMKL/script.simkl#65]
Not possible to re-login

**Comment by Simkl-dev** [comment]
You can try uninstalling and install the addon again

**Comment by SntNick** [comment]
I tried to reinstall the addon but the status is still logged in

**Comment by Simkl-dev** [comment]
Strange as it should uninstall all data. Could you please try uninstalling, and restarting kodi

**Comment by SntNick** [comment]
That's exactly what I tried with no luck :-(

**Comment by Simkl-dev** [comment]
When you click Uninstall, does it asks you to remove all data YES\NO?

**Comment by Simkl-dev** [comment]
Just tried uninstalling and selecting YES, remove settings. And then installing worked for me.

**Comment by SntNick** [comment]
Yep and I pressed "Yes"

**Comment by SntNick** [comment]
I will check again and add version info later. Apricate a quick response, mate

**Comment by Simkl-dev** [comment]
Do you have access to the addons folder on your Kodi? Try deleting the folder with Simkl settings

**Comment by SntNick** [comment]
Where should it be located on Windows 10?

**Comment by Simkl-dev** [comment]
https://forum.kodi.tv/showthread.php?tid=293445

**Comment by Simkl-dev** [comment]
https://kodi.wiki/view/Userdata

**Comment by Simkl-dev** [comment]
The second option is to delete the Kodi connection at https://simkl.com/settings/connected-apps/

**Comment by SntNick** [comment]
Nothing helps, sorry. Uninstall works fine, deleting the folder with Simkl settings. Disconnecting on simkl.com works fine, after installing the addon shows status "You are logged in" and doesn't show log in window when I click on "Please click to Log in"

**Comment by SntNick** [comment]
![image](https://user-images.githubusercontent.com/25370049/135472476-4ccc1cce-4b6a-4da0-bede-b6833964c1d1.png)

**Comment by SntNick** [comment]
![image](https://user-images.githubusercontent.com/25370049/135472619-4367070a-4117-4fe3-a7d9-2463d5f551c1.png)

**Comment by SntNick** [comment]
Also I've tried to reset the addon to defaults and it didn't help either

**Comment by Simkl-dev** [comment]
something is caching the result. I'm 100% sure that if you delete the settings folder it should not be possible to show that you are logged in. When you delete the folder, you need to exit the kodi server and check-in the task manager if Kodi is still running or not.

**Comment by SntNick** [comment]
Any other places I can check for the caching?

**Comment by ekleop** [comment]
did you remove?
C:\Users\**your username**\AppData\Roaming\Kodi\addons\script.simkl folder
here is located your token file C:\Users\**your username**\AppData\Roaming\Kodi\userdata\addon_data\script.simkl
then restart kodi

**Comment by SntNick** [comment]
Uninstalls removes the folders - I've checked, but after Kodi restart and SIMKL addon install the status is logged in again :-(

**Comment by Simkl-dev** [comment]
Check if you have installed kodi in another folder. They might be located in different folders if you have set one up using .exe and one kodi from the Windows app store.

**Comment by SntNick** [comment]
I've installed Kodi to non-system drive but the appdata folder belongs to the user anyway - so the paths you've described are the same for me. I've searched for any SIMKL stuff in the install folder too, but there is nothing alike.

**Comment by Simkl-dev** [comment]
Did you try clicking Please click to log in?

**Comment by SntNick** [comment]
Sure, but nothing happens

**Comment by Simkl-dev** [comment]
No more ideas other than re-installing kodi. I've added a task to add a Log out button for the future.

**Comment by SntNick** [comment]
Thanks anyway.

**Comment by ekleop** [comment]
C:\Users\ **username** \AppData\Roaming\Kodi\kodi.log
could you check the log file? 
it should have something like "login thread start = ", "Simkl: get setting token"
fields those start with "-- Simkl:"
So we can understand what happening there

**Comment by SntNick** [comment]
Thanks, will check tonight.

**Comment by SntNick** [comment]
The only line with "simkl" text in log file is "INFO <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: script.simkl v3.1.0 installed"

Kodi version is 19.1.0

**Comment by SntNick** [comment]
Debug log:
2021-10-03 19:34:03.226 T:10688   DEBUG <general>: CPythonInvoker(1, C:\Users\<User>\AppData\Roaming\Kodi\addons\script.simkl\service.py): the source file to load is "C:\Users\<User>\AppData\Roaming\Kodi\addons\script.simkl\service.py"
2021-10-03 19:34:03.227 T:10688   DEBUG <general>: CPythonInvoker(1, C:\Users\<User>\AppData\Roaming\Kodi\addons\script.simkl\service.py): setting the Python path to C:\Users\<User>\AppData\Roaming\Kodi\addons\script.simkl;E:\Program Files\Kodi\system\python\Lib;E:\Program Files\Kodi\python3.8.zip;E:\Program Files\Kodi\system\python\DLLs;E:\Program Files\Kodi;C:\Users\<User>\AppData\Roaming\Python\Python38\site-packages;E:\Program Files\Kodi\system\python;E:\Program Files\Kodi\system\python\lib\site-packages
2021-10-03 19:34:03.227 T:10688   DEBUG <general>: CPythonInvoker(1, C:\Users\<User>\AppData\Roaming\Kodi\addons\script.simkl\service.py): entering source directory C:\Users\<User>\AppData\Roaming\Kodi\addons\script.simkl
2021-10-03 19:34:03.227 T:10688   DEBUG <general>: CPythonInvoker(1, C:\Users\<User>\AppData\Roaming\Kodi\addons\script.simkl\service.py): instantiating addon using automatically obtained id of "script.simkl" dependent on version 3.0.0 of the xbmc.python api
2021-10-03 19:34:03.246 T:9872    DEBUG <general>: -->Python Interpreter Initialized<--

**Comment by SntNick** [comment]
2021-10-03 19:34:03.924 T:10688   DEBUG <general>: -- Simkl: dir = C:\Users\<User>\AppData\Roaming\Kodi\
2021-10-03 19:34:03.924 T:10688   DEBUG <general>: -- Simkl: Python Version = 3.8.5 (default, Feb 11 2021, 15:28:04) [MSC v.1928 64 bit (AMD64)]
2021-10-03 19:34:03.925 T:10688   DEBUG <general>: -- Simkl: args = ['']
2021-10-03 19:34:03.926 T:10688   DEBUG <CAddonSettings[script.simkl]>: trying to load setting definitions from old format...
2021-10-03 19:34:03.928 T:10688   DEBUG <general>: -- Simkl: get setting token =

**Comment by ekleop** [comment]
there isn't anything after "Simkl: get setting token =" line?
for example "Usersettings = " line

**Comment by SntNick** [comment]
Nothing

**Comment by ekleop** [comment]
yes,  it should be like this,  your device is unique so it was detected automatically

**Comment by assault88** [comment]
I've got this exact same problem. It says I'm logged in but also says Please click to log in, but when I click I don't get a login window. I've tried everything mentioned in this issue, how do I fix this?

**Comment by ekleop** [comment]
> I've got this exact same problem. It says I'm logged in but also says Please click to log in, but when I click I don't get a login window. I've tried everything mentioned in this issue, how do I fix this?

did you try everything above in this thread? 
tried to remove(with all data) and install it again?

what is your kodi version?

**Comment by assault88** [comment]
Yes I tried everything above in this thread. I've uninstalled, removed settings and the script.simkl folder, reinstalled but still the same. This didn't work for the last guy either. Kodi version was 19.1 when this stated happening, I tried upgrading Kodi to the latest 19.3 but no difference, the problem still exists.

**Comment by Simkl-dev** [comment]
Cannot reproduce on Windows. What's your OS, Kodi from the app store or from the website install? Are you able to check Kodi logs?

**Comment by assault88** [comment]
Kodi from the website on Windows 10 x64. Addon from the Kodi Respository.

Kodi logs show nothing of interest to do with Simkl addon except saying 3.1 is installed. 

I should say this started when I uninstalled and reinstalled the Simkl addon. Originally it was telling me I had no internet connection so wasn't updating my shows, so I uninstalled and reinstalled and that's when this happened.

**Comment by Simkl-dev** [comment]
Try disconnecting kodi on https://simkl.com/settings/connected-apps/ and re-login

**Comment by Simkl-dev** [comment]
then open https://simkl.com/pin/ - this should in theory auto-connect login if you're on the same wifi and app tried to generate a PIN.

**Comment by assault88** [comment]
I've disconnected Kodi as advised before. 

But I can't re-login. That is the problem. Clicking on "Please click to log in" in Simkl settings doesn't do anything. So no I can't enter a pin because I can't login.

**Comment by Simkl-dev** [comment]
https://troypoint.com/clear-kodi-cache/

https://www.comparitech.com/kodi/delete-kodi-addons/

**Comment by assault88** [comment]
I've deleted the Simkl addon, the addon userdata, and the Kodi cache, including the entire userdata folder. Reinstalled Simkl Addon and still the same. Says I'm logged in but also says "Please Click to Log in" but the login screen doesn't pop up when I click. Obviously I'm not logged in as the addon doesn't do anything anymore and the device is no longer linked to my Simkl account and I can't get a pin to re-add the device because I can't log in.

**Comment by ekleop** [comment]
could you dm to Ichika via Simkl discord channel?
https://discord.com/invite/u89XfYn
we can try to figure out where the problem is with teamviewer maybe

**Comment by assault88** [comment]
It's not completed. RT oblem still exists and has been unfixable.
