### ISSUE TITLE
Scrobbler Still Shows Bubble

### ISSUE THREAD

**Issue by kat953162** [SIMKL/script.simkl#7]
As of issues #2 and #3 it is rescrobbling on a timer. However, it keeps displaying that it is scrobbling every few minutes or so, which is annoying to the user who wants to watch a movie/show.

The only times it should pop up more than once is if it fails to connect to Simkl.

**Comment by kat953162** [comment]
I updated the addon from 0.2.1 to 0.2.3and it scrobbles more frequently than before.

I am fine with the scrobbling (because of the future Simkl updates), just not fine with the annoying bubble.

I will temporarily turn off the bubble completely until the issue is resolved.

**Comment by kat953162** [comment]
Correction: Can't turn off bubble because of #8

**Comment by daviddavo** [comment]
Can you please provide a log?

**Comment by kat953162** [comment]
So I installed version 0.2.3 but it shows 0.2.1.

**Comment by daviddavo** [comment]
Yes, i forgot to change it

**Comment by kat953162** [comment]
I tried everything but it says its 0.2.1 even though i install from 0.2.3 zip files

here is the log I sent in #3 and I will get another log in a second: http://paste.ubuntu.com/23731882/

**Comment by kat953162** [comment]
Here a new log (only the relevant parts) where it scrobbles twice: http://paste.ubuntu.com/23744952/

**Comment by kat953162** [comment]
16 but I have 17 installed too. Should I test it in Krypton?

**Comment by daviddavo** [comment]
No, no, I think I discovered the problem
Since I updated the code, there should be a new line in the log with "Time: {}, exp: {}, Dif: {}" format.
It isn't there, so the plugin is not updated. Try installing this file.
[script.simkl.zip](https://github.com/SIMKL/script.simkl/files/686981/script.simkl.zip)

**Comment by kat953162** [comment]
Will do

**Comment by kat953162** [comment]
Woops i closed this, Undoing

**Comment by kat953162** [comment]
Autoscrobble is locked (and I had it off from before).

I bypassed this by pressing "Defaults" at the bottom.

**Comment by daviddavo** [comment]
I locked it because it wasn't working properly (the deactivation of it) so it's default true. That means that you have the new version and it should work (even disable the bubble)

**Comment by kat953162** [comment]
It still scrobbled twice after using the version you sent me

**Comment by daviddavo** [comment]
And the new log? It's pretty rare, was working fine for me on Ubuntu

**Comment by kat953162** [comment]
Will grab a new log, hang on. I have Ubuntu on another partition (no Kodi on that), but I think the only relevance is Python version.

**Comment by daviddavo** [comment]
I just figured it out. It was a problem only present in Windows (because he uses '\' to separate directories).

New file: 
[script.simkl.zip](https://github.com/SIMKL/script.simkl/files/687090/script.simkl.zip)

**Comment by daviddavo** [comment]
Maybe you'll have to uninstall and reinstall the plugin

**Comment by kat953162** [comment]
I will try that. I have been uninstall/reuinstalling instead of just installing ontop of the old one.

I am pretty sure that windows uses "/" or "\" to separate directories

**Comment by kat953162** [comment]
The version you gave me says "You don't have internet" and the error check log message.
I reauthenticated with the pin and so I stopped getting that message (to be fair, it might have actually disconnected).

I receive a Simkl Tracker error every few minutes. I am going to send you the latest log.

**Comment by kat953162** [comment]
It attempts and fails to scrobble *once* which means that what you did with the bubble worked but broke the actual scrobble function. log: http://paste.ubuntu.com/23745639/

**Comment by daviddavo** [comment]
Try now (Btw: thanks for helping with the project)
[script.simkl.zip](https://github.com/SIMKL/script.simkl/files/687220/script.simkl.zip)

**Comment by kat953162** [comment]
That error must have been because of my crappy internet. It works fine now.

Also it appears to have only displayed the Scrobble message once! Going to close this issue after one more test.

**Comment by daviddavo** [comment]
Woah, that's another error, caused by an slow connection. I'll document it as #9

**Comment by kat953162** [comment]
It appears to have been fixed!

**Comment by daviddavo** [comment]
Btw, you can always reopen an issue instead of creating a new one

**Comment by kat953162** [comment]
I couldn't reopen issues before, but I asked Masyk to give me collaborator access to the github page. Now I have a reopen button for comments.

**Comment by ekleop** [comment]
http://take.ms/7JVhj
now it keeps scrobbling(maybe  file is not locked properly) every n seconds, but bubble is shown once and then every time when I try to rewind

**Comment by kat953162** [comment]
ekleop: this is a duplicate issue with #2 . Install this file: [likely fixed version](https://github.com/SIMKL/script.simkl/files/687220/script.simkl.zip) and make sure to pastebin the relevant part of your Kodi log, not screenshot it. [This is an excellent Pastebin](http://paste.ubuntu.com)

**Comment by ekleop** [comment]
Yes, this thread is a duplicate so there is no matter what to reopen) 
it's really the latest version 0.2.3,  I'm not using zip, just cloned the repository and installed from there, furthermore it's worked  in previous version and there was "file locked" line in the log file, now there isn't.
Why I'm not using pastebin? matter of habit I think, no problem, will use it

**Comment by kat953162** [comment]
ekleop: Github went down and I sent you in an email:

There are multiple versions of 0.2.3 because David Davo and I worked on the rescrobbling bug. The latest version was that zip I sent and I don't believe David Davo set it to the correct latest version. 

For the pastebin thing, it's usually easier for coders like me to understand it if it is plain text :)

**Comment by ekleop** [comment]
Yes, you were right. Zip version is the latest one. I just used to download sources from Git bacause usually it's most recent than any other code.
