### ISSUE TITLE
Not possible to use on multiple Kodi installations

### ISSUE THREAD

**Issue by shotfirer** [SIMKL/script.simkl#71]
I have Kodi installed on two devices. It appears that only one at a time can have the scrobbler. Every time I launch the other Kodi installation it asks me to activate it with pin again.

**Comment by shotfirer** [comment]
Steps to reproduce: Install Kodi on two different devices. Install the scrobbler on both of them. Launch Kodi on any device, and authorize the scrobbler with a pin. Launch the Kodi on another device, and authorize the scrobbler. Go back to the first device, launch Kodi - and the scrobbler will ask for the authorization again.

**Comment by ekleop** [comment]
check it now, should be fine
